### ISSUE TITLE
The method builder() is undefined for the type Mailing

### ISSUE THREAD

**Issue by javisnow** [ottlinger/mailversendala#14]
Hello, 
I downloaded the mailvesendala and import in my workspace in eclipse.

I have the error -> The method builder() is undefined for the type Mailing

What can I do to solve this ?

![method-builder-is-undefined](https://user-images.githubusercontent.com/12116618/30565748-c66ff426-9cc9-11e7-8247-ccb73b4ea7e2.png)

**Comment by ottlinger** [comment]
The project relies on Lombok / https://projectlombok.org/, which means that your IDE needs to be prepared to work with it.
In case of Eclipse you need to add lombok to its classpath https://projectlombok.org/setup/eclipse.
IntelliJ has a plugin.

I'll add this to the project's documentation - thanks for raising the issue.
